### ISSUE TITLE
worldpreview not generating any chunks on certain seeds

### ISSUE THREAD

**Issue by binkus-underscore** [KingContaria/seedqueue#10]
log:
https://github.com/user-attachments/files/16570751/latest.log
example:
https://streamable.com/r39jnm

**Comment by binkus-underscore** [comment]
[seedqueue.json](https://github.com/user-attachments/files/16570803/seedqueue.json)
config ^

**Comment by Crystal15118** [comment]
> log: https://github.com/user-attachments/files/16570751/latest.log example: https://streamable.com/r39jnm

your world gen% is set to 0 which might be causing this i would recommend having it between 10-20%

**Comment by Crystal15118** [comment]
also enable smooth chunk building

**Comment by KingContaria** [comment]
This has been fixed as of SeedQueue 1.3 and WorldPreview 6.2
