### ISSUE TITLE
Ability to schedule joining instances

### ISSUE THREAD

**Issue by jojoe77777** [KingContaria/seedqueue#16]
I would like to be able to double click my "enter instance" key to schedule a join for a preview. 
This means that when the preview is nearly finished (roughly 300-500ms before joining) it plays a warning sound, and when it finished generating the player is automatically put in the world.
~~Additionally, double clicking (<300ms) my "enter instance" or "focus reset" hotkeys should schedule joins for all locked instances~~

I have implemented this for myself using a python script to spam the Play Next Lock hotkey, but it would be a good addition to SeedQueue itself

~~It would also be very useful if the world gen % of the highest instance with a scheduled join was able to be displayed in some way, either by rendering it on the wall screen or outputting it to a text file for macros/OBS to handle it.
The purpose of this is so you can position the % number in the middle of a a 3x3 main grid, and when the number is nearly at 100% you know you're about to be put into a seed~~

**Comment by KingContaria** [comment]
How do you expect the warning sound to work? play a warning sound when the instance finishes loading, wait, then put into the seed or estimate the time to finish and send the warning 300-500ms before that?

Double clicking seems like a good suggestion for https://github.com/KingContaria/seedqueue/issues/3.

Last point is a bit unrelated to scheduling join, either a good fit for another issue, for example the percentages could be included in the wall stateoutput.
To render it directly in Minecraft, suggest in https://github.com/KingContaria/seedqueue/issues/4, its not exactly the same thing but ive been considering having something like "text sources" included in transformations and they could potentially have different sources, for example 'highestlockedworldgenpercentage', id be open to implement fairly personalized things for something like that.

For future discussion I'll treat this only as a suggestion to be able to schedule individual or all instances and have a warning sound before putting you into the world.
Am i understanding correctly that you want to be able to schedule multiple enters, basically acting as a way to bypass the wall screen without the option enabled?

**Comment by jojoe77777** [comment]
For the warning sound it would be fine to just play it around 95% world gen (configurable)

> Am i understanding correctly that you want to be able to schedule multiple enters, basically acting as a way to bypass the wall screen without the option enabled?
Scheduling an enter would also lock it, so having wall bypass enabled would handle that aspect of it. The "scheduled enters" should be forgotten once an instance is entered (going back to wall shouldn't put you in a world 500ms later when one loads), but they should stay locked

**Comment by KingContaria** [comment]
Started work on this here: https://github.com/KingContaria/seedqueue/tree/feature/schedule-joins

Should scheduling a ready instance to be joined act the same as playing it? If not, how else would you like it to be handled?
I'm also not sure how i want the warning percentage to be configured yet, I don't want to clutter the settings menu with stuff that only takes effect with resourcepacks so i might make it part of the sounds .mcmeta file.

**Comment by jojoe77777** [comment]
> Should scheduling a ready instance to be joined act the same as playing it?
Yes
