### ISSUE TITLE
Ocasionally getting no sound in game

### ISSUE THREAD

**Issue by Priffin** [KingContaria/seedqueue#17]
[latest.log](https://github.com/user-attachments/files/16571435/latest.log)

[04:12:47] [Sound engine/WARN]: Maximum sound pool size 247 reached
[04:12:47] [Render thread/WARN]: Failed to create new sound handle

https://cdn.discordapp.com/attachments/1263997861620617407/1271653200264560710/mute_sounds.zip?ex=66b8c795&is=66b77615&hm=34b489d2b1a2afe86614e5948acbe8f6f490acdd0704fe58abb4992cabdf4a34&

using this to disable rest and lock sounds

**Comment by KingContaria** [comment]
minecraft doesnt handle the empty sound files very well, for future readers please use a silent sound instead

**Comment by tildejustin** [comment]
given multiple people tried this, I think it would be helpful if 0 byte sound files were a runtime exception.

**Comment by KingContaria** [comment]
not a bad idea, i'll reopen
