### ISSUE TITLE
Lock Icons with mac resolution on windowed

### ISSUE THREAD

**Issue by tlqhm** [KingContaria/seedqueue#23]
I have a macbook pro 14" with a 3024x1832 in game windowed resolution
my max world generation is set to 20% 

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/683affaa-c41d-4972-8d97-30d339c2eddf">

In the first image with 9 worlds on wall, 4 of them are fully generated (locked previews) and 5 are at 20%
out of the 4 locked worlds only 1 of them has an icon and it is much larger than it should be 

The default simulated window size was 1512x916 (50% of in game resolution on each dimension)
I have tried 3024x1832, and 1920x1080. All the resolutions have the same behavior 

However the icons function correctly in fullscreen as shown in the 2nd image. It is only windowed that causes this behavior.

![image](https://github.com/user-attachments/assets/654c7fbb-c1ef-483e-9b5d-6fde7378501f)

**Comment by KingContaria** [comment]
could you send your seedqueue and standardsettings config files?
you can find them in .minecraft/config/mcsr/
could you also check if setting your Gui Scale to 1 in StandardSettings fixes your issue?

**Comment by tildejustin** [comment]
are you using retino?

**Comment by KingContaria** [comment]
Fixed by https://github.com/KingContaria/seedqueue/commit/8cc9e3f1db363c8b2d905fe4c623a8cd7344144a, forgot to add that to the commit message
