### ISSUE TITLE
Seedqueue prevent coop.

### ISSUE THREAD

**Issue by masarta0129** [KingContaria/seedqueue#24]
https://youtu.be/YYNzyfgMuOg

**Comment by tildejustin** [comment]
can you provide a log from the host and the person trying to join?

**Comment by masarta0129** [comment]
masa [todaylog.zip](https://github.com/user-attachments/files/16575642/todaylog.zip)
harusame [2024-08-12-3.log.zip](https://github.com/user-attachments/files/16575644/2024-08-12-3.log.zip)
 sending some logs because I forgot which ones.

**Comment by tildejustin** [comment]
hmm, doesn't seem to be anything particularly useful in logs, i'll see if i can reproduce the issue locally.

**Comment by tildejustin** [comment]
"[14:06:40] [Worker-Main-2/ERROR]: Signature is missing from textures payload" in log of joining instance but it worked 🤔

**Comment by masarta0129** [comment]
I tried again and it was successful
I'm really sorry for the trouble.

**Comment by KingContaria** [comment]
Closing this for now, if it should come up again feel free to comment again :)
