### ISSUE TITLE
Very high CPU usage while idling

### ISSUE THREAD

**Issue by marin774** [KingContaria/seedqueue#29]
After playing and resetting for even a few minutes, CPU usage will be large when idling, sometimes hitting 30% on my pc. This also happens while idling on SQ wall (after all queued instances have stopped loading).
![image](https://github.com/user-attachments/assets/9f572ab6-7030-46be-a04a-24214dd371f5)

**Comment by marin774** [comment]
Logs are [here](https://mclo.gs/x4X0VcT) (i ran a benchmark, then quit to title, currently sitting at 10% cpu usage with "very high" power usage), but I don't think there's anything useful in the logs.
If i had to guess, some threads are stuck in a loop doing something in the background..

**Comment by KingContaria** [comment]
SeedQueue disables one of SleepBackgrounds optimizations that was designed to reduce CPU usage when idling because it caused severe slowdowns when SeedQueue was running at high load, there is a good chance thats the cause. I might look into only disabling it while in a SeedQueue session

**Comment by marin774** [comment]
I had SleepBackground disabled there, but it still might have something to do with that ¯\_(ツ)_/¯

**Comment by KingContaria** [comment]
Was this issue fixed by version 1.1.1?

**Comment by marin774** [comment]
Yes, 1.1.1 fixed this
