### ISSUE TITLE
Save some played worlds to mitigate damage from accidental resets

### ISSUE THREAD

**Issue by maskersss** [KingContaria/seedqueue#33]
a way to implement it would be to save the world if it has been played for more than X minutes (igt?)

**Comment by KingContaria** [comment]
Could you write down some reproduction steps, I can't manage to reproduce your issue by playing an instance from the wall screen and instantly resetting it using the Atum reset key. If that's what you did, could you send a world file of one of these played but hidden worlds?

**Comment by maskersss** [comment]
"press gold boots, load into a world, break dirt below you, reset with a hotkey, load into the next seed, `stop resets & quit`, load into the previous world from singleplayer, find dirt not broken" is what i did

> but hidden worlds

it's not hidden for me, it just didn't save
