### ISSUE TITLE
Play sound on atum reset

### ISSUE THREAD

**Issue by breadworms** [KingContaria/seedqueue#37]
Hi, would it be possible to add a new sound that would play when atum resets (f6), i.e. a sound that plays when the player resets the current playing instance.

A very non serious suggestion for a specific setup I wanted :p

**Comment by KingContaria** [comment]
I'd like to keep seedqueue sounds close to seedqueue code, however i could consider adding sounds for joining wall and bypassing wall.

**Comment by KingContaria** [comment]
Unless I'm missing something, setting both these sounds to the same one would essentially act as a reset sound while allowing for more customization and keeping the policy of only implementing customization around seedqueues functionality.
