### ISSUE TITLE
print configs in the log

### ISSUE THREAD

**Issue by maskersss** [KingContaria/seedqueue#39]
can replace potential julti 'Zip Instance Debug Files'
idk what exactly would make sense to include, wp & sq configs and java path / args?
idk if it makes more sense to just print once on launch or print every time on config change too

java path / args are included in the full instance log in mmc / prism, but would be nice to have them in latest.log too
idk if how much sense it makes to include in seedqueue, but i dont really see why not

**Comment by KingContaria** [comment]
It wouldnt make sense to only print options on launch because there wouldnt be any guarantee theyd be the same but I'd also rather not spam the log with logging settings.
Java settings could be useful and would only have to be printed once.
If i were to implement something like this I'd want it to be something like a "Dump Debug Info" button, but I'm not sure it's appropriate to add to SeedQueue. People would still have to copy a file, so I don't think having to send less files would warrant putting it into a mod.
I might change my mind on this but thats my thoughts for now

**Comment by maskersss** [comment]
also maybe hardware, stealing the idea from ravalle from discord

> It wouldnt make sense to only print options on launch because there wouldnt be any guarantee theyd be the same

better than nothing i guess? not spamming the logs is fair yeah

> People would still have to copy a file

you can send logs through GUI in mmc/prism and it's potentially smth people are used to, but i agree that sending a few files isn't hard

**Comment by KingContaria** [comment]
> also maybe hardware, stealing the idea from ravalle from discord

Would definitely be helpful, not sure if there'd be privacy concerns with that tho.

> better than nothing i guess? not spamming the logs is fair yeah

False information is worse than just requesting the user to send the file imo

**Comment by joe-ldp** [comment]
Might be a good option to print benchmark results (RPS) & hardware, config, etc. to a file after completing a benchmark.

This way you can just tell a user to benchmark and you get 1. an idea of their performance and 2. their hardware & config.

**Comment by maskersss** [comment]
> not sure if there'd be privacy concerns with that tho

mainstream sodium prints the gpu for me to latest.log, so while i'm rather clueless, i don't see this being an issue

**Comment by Crystal15118** [comment]
> not sure if there'd be privacy concerns with that tho.

you could ask that by a poll in the SeedQueue discord?

**Comment by KingContaria** [comment]
I asked in the fabric discord and it seems fairly common practice, plus that info is printed to crash-reports aswell, so I'd conclude that it's fine to implement. I'm open to a PR that implements logging Hardware + Java Settings at startup.

**Comment by Crystal15118** [comment]
> I asked in the fabric discord and it seems fairly common practice, plus that info is printed to crash-reports aswell, so I'd conclude that it's fine to implement. I'm open to a PR that implements logging Hardware + Java Settings at startup.

i have the code just let me test it and if it works i'll send  a pr
