### ISSUE TITLE
HEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEELP

### ISSUE THREAD

**Issue by demelovesgoats** [KingContaria/seedqueue#52]
![Screenshot 2024-08-14 121441](https://github.com/user-attachments/assets/757ed6a1-bc41-4a10-8665-59ca5d0ea7fe)

**Comment by Crystal15118** [comment]
do what the message suggests:
> Remove illegal mods for minecraft speedrunning (they aren't compatible with SeedQueue)
> Remove fabric api
> Update fabric loader to 0.16.0 or above

**Comment by KingContaria** [comment]
Hi, there is a couple issues with your setup.
Firstly, you have to update to Fabric Loader 0.16, secondly you are using Fabric API which is not allowed for speedrunning.
Please join the [discord](https://discord.gg/9P6PJkHCdU) if you need help setting up the mod!
