### ISSUE TITLE
overlay.png size issues

### ISSUE THREAD

**Issue by sylqie** [KingContaria/seedqueue#60]
hello! earlier, i asked about this in the discord and was told to create an issue here and send files for further discussion!

the issue is that the overlay.png doesn't scale correctly relative to my monitor (1080p), but then i soon figured out it had something to do with the "simulated window size" option and i'm assuming the image scales based on the resolution i set there, so i resized the image a couple times till it fit.

but that eventually led to this issue: https://discord.com/channels/1262887973154848828/1262901524619595887/1274709638801129483

the resourcepack attached doesn't completely match the one in the video, but it should have the same results (observe the stars on the top left and bottom right)

[queueMaki.zip](https://github.com/user-attachments/files/16653257/queueMaki.zip)
[seedqueue.json](https://github.com/user-attachments/files/16653258/seedqueue.json)

**Comment by KingContaria** [comment]
Will be fixed in the next version of SeedQueue
