### ISSUE TITLE
Bug: Focus Reset creates a blank space on the next set of previews when using a lock group.

### ISSUE THREAD

**Issue by sathya-pramodh** [KingContaria/seedqueue#72]
Video

https://github.com/user-attachments/assets/4f803be6-2c3a-4f5c-83f3-c1b122e18cb4

# Expected behaviour
Focused Preview is locked and the next set of previews are the same amount as defined by the config.

**Comment by KingContaria** [comment]
This happens because `SeedQueueWallScreen#blockedMainPositions` is cleared when focus reset is pressed, but the locked preview is only moved to the locked group at the start of the next frame in `updatePreparingPreviews`.
