### ISSUE TITLE
Resource Packs - "replaceLockedInstances": false flag not respected 

### ISSUE THREAD

**Issue by therowdie** [KingContaria/seedqueue#75]
v1.3 not backwards compatible with existing resource packs'   _"replaceLockedInstances": false_ flag
resource packs that have  _"replaceLockedInstances": false_ still replace locked instances

**Comment by KingContaria** [comment]
This is a regression caused by https://github.com/KingContaria/seedqueue/commit/a1c4628eb9e1d1341af537afc77ab81b833d4795 which was meant to fix https://github.com/KingContaria/seedqueue/issues/72
